# -*- coding: utf-8 -*-
"""Die Saetze des Reiters "My times", in allen 25 Sprachen.

Am 2026-09-24 dazugekommen. ZUSATZ-Modul nach Schluessel: jede Uebersetzung
steht NEBEN ihrem englischen Satz, nicht an einer Listenposition -- bei 31
Saetzen waere eine verrutschte Position nicht zu sehen und verschoebe alle
folgenden.

Diese Uebersetzungen sind nicht von Muttersprachlern geprueft.
"""

LANG = "{0} lap(s) on {1} course(s), of {2} recorded. Assists, gearbox and valid/invalid are leaderboard facts the telemetry does not send, so they cannot filter your own laps."

# Spalten: Schluessel -> {sprache: text}. Eine Zeile je Satz, damit man beim
# Lesen sieht, ob alle Sprachen dieselbe Bedeutung tragen.
T = {
 "Apply": {"de":"Übernehmen","fr":"Appliquer","es":"Aplicar","it":"Applica","pt":"Aplicar","nl":"Toepassen","pl":"Zastosuj","sv":"Använd","da":"Anvend","fi":"Käytä","cs":"Použít","hu":"Alkalmaz","ro":"Aplică","el":"Εφαρμογή","ru":"Применить","tr":"Uygula","id":"Terapkan","ms":"Guna","vi":"Áp dụng","th":"ใช้","ja":"適用","ko":"적용","zh-Hans":"应用","zh-Hant":"套用"},
 "Category": {"de":"Kategorie","fr":"Catégorie","es":"Categoría","it":"Categoria","pt":"Categoria","nl":"Categorie","pl":"Kategoria","sv":"Kategori","da":"Kategori","fi":"Luokka","cs":"Kategorie","hu":"Kategória","ro":"Categorie","el":"Κατηγορία","ru":"Категория","tr":"Kategori","id":"Kategori","ms":"Kategori","vi":"Thể loại","th":"หมวดหมู่","ja":"カテゴリー","ko":"카테고리","zh-Hans":"类别","zh-Hant":"類別"},
 "Class": {"de":"Klasse","fr":"Classe","es":"Clase","it":"Classe","pt":"Classe","nl":"Klasse","pl":"Klasa","sv":"Klass","da":"Klasse","fi":"Luokka","cs":"Třída","hu":"Osztály","ro":"Clasă","el":"Κλάση","ru":"Класс","tr":"Sınıf","id":"Kelas","ms":"Kelas","vi":"Hạng","th":"คลาส","ja":"クラス","ko":"클래스","zh-Hans":"等级","zh-Hant":"等級"},
 "Country": {"de":"Land","fr":"Pays","es":"País","it":"Paese","pt":"País","nl":"Land","pl":"Kraj","sv":"Land","da":"Land","fi":"Maa","cs":"Země","hu":"Ország","ro":"Țară","el":"Χώρα","ru":"Страна","tr":"Ülke","id":"Negara","ms":"Negara","vi":"Quốc gia","th":"ประเทศ","ja":"国","ko":"국가","zh-Hans":"国家","zh-Hant":"國家"},
 "Course": {"de":"Kurs","fr":"Parcours","es":"Circuito","it":"Percorso","pt":"Percurso","nl":"Parcours","pl":"Trasa","sv":"Bana","da":"Bane","fi":"Rata","cs":"Trať","hu":"Pálya","ro":"Traseu","el":"Διαδρομή","ru":"Трасса","tr":"Parkur","id":"Lintasan","ms":"Litar","vi":"Đường đua","th":"สนาม","ja":"コース","ko":"코스","zh-Hans":"赛道","zh-Hant":"賽道"},
 "Date": {"de":"Datum","fr":"Date","es":"Fecha","it":"Data","pt":"Data","nl":"Datum","pl":"Data","sv":"Datum","da":"Dato","fi":"Päivä","cs":"Datum","hu":"Dátum","ro":"Dată","el":"Ημερομηνία","ru":"Дата","tr":"Tarih","id":"Tanggal","ms":"Tarikh","vi":"Ngày","th":"วันที่","ja":"日付","ko":"날짜","zh-Hans":"日期","zh-Hant":"日期"},
 "Gap": {"de":"Abstand","fr":"Écart","es":"Diferencia","it":"Distacco","pt":"Diferença","nl":"Verschil","pl":"Strata","sv":"Avstånd","da":"Afstand","fi":"Ero","cs":"Ztráta","hu":"Különbség","ro":"Diferență","el":"Διαφορά","ru":"Отставание","tr":"Fark","id":"Selisih","ms":"Jurang","vi":"Khoảng cách","th":"ห่าง","ja":"差","ko":"차이","zh-Hans":"差距","zh-Hant":"差距"},
 "Make": {"de":"Marke","fr":"Marque","es":"Marca","it":"Marca","pt":"Marca","nl":"Merk","pl":"Marka","sv":"Märke","da":"Mærke","fi":"Merkki","cs":"Značka","hu":"Márka","ro":"Marcă","el":"Μάρκα","ru":"Марка","tr":"Marka","id":"Merek","ms":"Jenama","vi":"Hãng","th":"ยี่ห้อ","ja":"メーカー","ko":"제조사","zh-Hans":"品牌","zh-Hant":"品牌"},
 "Mode": {"de":"Modus","fr":"Mode","es":"Modo","it":"Modalità","pt":"Modo","nl":"Modus","pl":"Tryb","sv":"Läge","da":"Tilstand","fi":"Tila","cs":"Režim","hu":"Mód","ro":"Mod","el":"Λειτουργία","ru":"Режим","tr":"Mod","id":"Mode","ms":"Mod","vi":"Chế độ","th":"โหมด","ja":"モード","ko":"모드","zh-Hans":"模式","zh-Hant":"模式"},
 "Reset": {"de":"Zurücksetzen","fr":"Réinitialiser","es":"Restablecer","it":"Azzera","pt":"Repor","nl":"Herstellen","pl":"Resetuj","sv":"Återställ","da":"Nulstil","fi":"Nollaa","cs":"Obnovit","hu":"Visszaállítás","ro":"Resetează","el":"Επαναφορά","ru":"Сбросить","tr":"Sıfırla","id":"Atur ulang","ms":"Tetap semula","vi":"Đặt lại","th":"รีเซ็ต","ja":"リセット","ko":"초기화","zh-Hans":"重置","zh-Hant":"重設"},
 "Start": {"de":"Start","fr":"Départ","es":"Salida","it":"Partenza","pt":"Partida","nl":"Start","pl":"Start","sv":"Start","da":"Start","fi":"Lähtö","cs":"Start","hu":"Rajt","ro":"Start","el":"Εκκίνηση","ru":"Старт","tr":"Başlangıç","id":"Start","ms":"Mula","vi":"Xuất phát","th":"ออกตัว","ja":"スタート","ko":"출발","zh-Hans":"起步","zh-Hant":"起步"},
 "Time": {"de":"Zeit","fr":"Temps","es":"Tiempo","it":"Tempo","pt":"Tempo","nl":"Tijd","pl":"Czas","sv":"Tid","da":"Tid","fi":"Aika","cs":"Čas","hu":"Idő","ro":"Timp","el":"Χρόνος","ru":"Время","tr":"Süre","id":"Waktu","ms":"Masa","vi":"Thời gian","th":"เวลา","ja":"タイム","ko":"시간","zh-Hans":"时间","zh-Hant":"時間"},
 "Tune": {"de":"Abstimmung","fr":"Réglage","es":"Ajuste","it":"Assetto","pt":"Afinação","nl":"Afstelling","pl":"Ustawienia","sv":"Inställning","da":"Opsætning","fi":"Viritys","cs":"Nastavení","hu":"Beállítás","ro":"Reglaj","el":"Ρύθμιση","ru":"Настройка","tr":"Ayar","id":"Setelan","ms":"Tetapan","vi":"Tinh chỉnh","th":"การปรับแต่ง","ja":"チューン","ko":"튜닝","zh-Hans":"调校","zh-Hant":"調校"},
 "Type": {"de":"Typ","fr":"Type","es":"Tipo","it":"Tipo","pt":"Tipo","nl":"Type","pl":"Typ","sv":"Typ","da":"Type","fi":"Tyyppi","cs":"Typ","hu":"Típus","ro":"Tip","el":"Τύπος","ru":"Тип","tr":"Tür","id":"Jenis","ms":"Jenis","vi":"Loại","th":"ประเภท","ja":"タイプ","ko":"유형","zh-Hans":"类型","zh-Hant":"類型"},
 "Year": {"de":"Baujahr","fr":"Année","es":"Año","it":"Anno","pt":"Ano","nl":"Bouwjaar","pl":"Rok","sv":"År","da":"År","fi":"Vuosi","cs":"Rok","hu":"Év","ro":"An","el":"Έτος","ru":"Год","tr":"Yıl","id":"Tahun","ms":"Tahun","vi":"Năm","th":"ปี","ja":"年式","ko":"연식","zh-Hans":"年份","zh-Hant":"年份"},
 "all": {"de":"alle","fr":"tous","es":"todos","it":"tutti","pt":"todos","nl":"alle","pl":"wszystkie","sv":"alla","da":"alle","fi":"kaikki","cs":"vše","hu":"mind","ro":"toate","el":"όλα","ru":"все","tr":"tümü","id":"semua","ms":"semua","vi":"tất cả","th":"ทั้งหมด","ja":"すべて","ko":"전체","zh-Hans":"全部","zh-Hant":"全部"},
 "any start": {"de":"jeder Start","fr":"tout départ","es":"cualquier salida","it":"qualsiasi partenza","pt":"qualquer partida","nl":"elke start","pl":"dowolny start","sv":"alla starter","da":"alle starter","fi":"mikä tahansa lähtö","cs":"jakýkoli start","hu":"bármilyen rajt","ro":"orice start","el":"οποιαδήποτε εκκίνηση","ru":"любой старт","tr":"her başlangıç","id":"semua start","ms":"sebarang mula","vi":"mọi kiểu xuất phát","th":"ทุกแบบออกตัว","ja":"全スタート","ko":"모든 출발","zh-Hans":"任意起步","zh-Hant":"任意起步"},
 "best per car and course": {"de":"beste je Auto und Kurs","fr":"meilleur par voiture et parcours","es":"mejor por coche y circuito","it":"migliore per auto e percorso","pt":"melhor por carro e percurso","nl":"beste per auto en parcours","pl":"najlepszy dla auta i trasy","sv":"bästa per bil och bana","da":"bedste pr. bil og bane","fi":"paras autoa ja rataa kohden","cs":"nejlepší pro auto a trať","hu":"legjobb autónként és pályánként","ro":"cel mai bun pe mașină și traseu","el":"καλύτερος ανά αυτοκίνητο και διαδρομή","ru":"лучший по машине и трассе","tr":"araba ve parkur başına en iyi","id":"terbaik per mobil dan lintasan","ms":"terbaik bagi setiap kereta dan litar","vi":"tốt nhất theo xe và đường đua","th":"ดีที่สุดต่อรถและสนาม","ja":"車とコースごとのベスト","ko":"차량·코스별 최고","zh-Hans":"每车每赛道最佳","zh-Hant":"每車每賽道最佳"},
 "down": {"de":"abgestuft","fr":"déclassée","es":"rebajado","it":"declassata","pt":"rebaixado","nl":"lager","pl":"obniżona","sv":"nedgraderad","da":"nedgraderet","fi":"alennettu","cs":"snížená","hu":"lefokozva","ro":"retrogradată","el":"υποβαθμισμένο","ru":"ниже","tr":"düşürülmüş","id":"diturunkan","ms":"diturunkan","vi":"hạ cấp","th":"ลดคลาส","ja":"クラスダウン","ko":"등급 하향","zh-Hans":"降级","zh-Hant":"降級"},
 "flying": {"de":"fliegend","fr":"lancé","es":"lanzada","it":"lanciata","pt":"lançada","nl":"vliegend","pl":"lotny","sv":"flygande","da":"flyvende","fi":"lentävä","cs":"letmý","hu":"repülő","ro":"lansat","el":"ιπτάμενη","ru":"с ходу","tr":"hareketli","id":"melaju","ms":"berlari","vi":"xuất phát bay","th":"ออกตัวขณะวิ่ง","ja":"フライング","ko":"주행 출발","zh-Hans":"行进起步","zh-Hant":"行進起步"},
 "from": {"de":"von","fr":"de","es":"desde","it":"da","pt":"de","nl":"van","pl":"od","sv":"från","da":"fra","fi":"alkaen","cs":"od","hu":"-tól","ro":"de la","el":"από","ru":"с","tr":"başlangıç","id":"dari","ms":"dari","vi":"từ","th":"จาก","ja":"から","ko":"부터","zh-Hans":"从","zh-Hant":"從"},
 "laps": {"de":"Runden","fr":"tours","es":"vueltas","it":"giri","pt":"voltas","nl":"ronden","pl":"okrążenia","sv":"varv","da":"omgange","fi":"kierrokset","cs":"kola","hu":"körök","ro":"tururi","el":"γύροι","ru":"круги","tr":"turlar","id":"putaran","ms":"pusingan","vi":"vòng","th":"รอบ","ja":"周回","ko":"랩","zh-Hans":"圈","zh-Hant":"圈"},
 "laps and sprints": {"de":"Runden und Sprints","fr":"tours et sprints","es":"vueltas y sprints","it":"giri e sprint","pt":"voltas e sprints","nl":"ronden en sprints","pl":"okrążenia i sprinty","sv":"varv och sprinter","da":"omgange og sprint","fi":"kierrokset ja sprintit","cs":"kola a sprinty","hu":"körök és sprintek","ro":"tururi și sprinturi","el":"γύροι και σπριντ","ru":"круги и спринты","tr":"turlar ve sprintler","id":"putaran dan sprint","ms":"pusingan dan pecut","vi":"vòng và nước rút","th":"รอบและสปรินต์","ja":"周回とスプリント","ko":"랩과 스프린트","zh-Hans":"圈与冲刺","zh-Hant":"圈與衝刺"},
 "search car": {"de":"Auto suchen","fr":"chercher une voiture","es":"buscar coche","it":"cerca auto","pt":"procurar carro","nl":"auto zoeken","pl":"szukaj auta","sv":"sök bil","da":"søg bil","fi":"hae autoa","cs":"hledat auto","hu":"autó keresése","ro":"caută mașina","el":"αναζήτηση αυτοκινήτου","ru":"поиск машины","tr":"araba ara","id":"cari mobil","ms":"cari kereta","vi":"tìm xe","th":"ค้นหารถ","ja":"車を検索","ko":"차량 검색","zh-Hans":"搜索车辆","zh-Hant":"搜尋車輛"},
 "sprint": {"de":"Sprint","fr":"sprint","es":"sprint","it":"sprint","pt":"sprint","nl":"sprint","pl":"sprint","sv":"sprint","da":"sprint","fi":"sprintti","cs":"sprint","hu":"sprint","ro":"sprint","el":"σπριντ","ru":"спринт","tr":"sprint","id":"sprint","ms":"pecut","vi":"nước rút","th":"สปรินต์","ja":"スプリント","ko":"스프린트","zh-Hans":"冲刺","zh-Hant":"衝刺"},
 "sprints": {"de":"Sprints","fr":"sprints","es":"sprints","it":"sprint","pt":"sprints","nl":"sprints","pl":"sprinty","sv":"sprinter","da":"sprint","fi":"sprintit","cs":"sprinty","hu":"sprintek","ro":"sprinturi","el":"σπριντ","ru":"спринты","tr":"sprintler","id":"sprint","ms":"pecut","vi":"nước rút","th":"สปรินต์","ja":"スプリント","ko":"스프린트","zh-Hans":"冲刺","zh-Hant":"衝刺"},
 "standing": {"de":"stehend","fr":"arrêté","es":"parada","it":"da fermo","pt":"parada","nl":"staand","pl":"z miejsca","sv":"stående","da":"stående","fi":"paikaltaan","cs":"z místa","hu":"álló","ro":"de pe loc","el":"από στάση","ru":"с места","tr":"duran","id":"diam","ms":"pegun","vi":"xuất phát đứng","th":"ออกตัวจากหยุดนิ่ง","ja":"スタンディング","ko":"정지 출발","zh-Hans":"静止起步","zh-Hant":"靜止起步"},
 "stock class": {"de":"Serienklasse","fr":"classe d'origine","es":"clase de serie","it":"classe di serie","pt":"classe de série","nl":"standaardklasse","pl":"klasa fabryczna","sv":"standardklass","da":"standardklasse","fi":"vakioluokka","cs":"sériová třída","hu":"gyári osztály","ro":"clasă de serie","el":"εργοστασιακή κλάση","ru":"стоковый класс","tr":"standart sınıf","id":"kelas standar","ms":"kelas asal","vi":"hạng nguyên bản","th":"คลาสเดิม","ja":"標準クラス","ko":"순정 클래스","zh-Hans":"原厂等级","zh-Hant":"原廠等級"},
 "to": {"de":"bis","fr":"à","es":"hasta","it":"a","pt":"até","nl":"tot","pl":"do","sv":"till","da":"til","fi":"asti","cs":"do","hu":"-ig","ro":"până la","el":"έως","ru":"по","tr":"bitiş","id":"sampai","ms":"hingga","vi":"đến","th":"ถึง","ja":"まで","ko":"까지","zh-Hans":"到","zh-Hant":"到"},
 "up": {"de":"hochgestuft","fr":"surclassée","es":"subido","it":"promossa","pt":"subido","nl":"hoger","pl":"podwyższona","sv":"uppgraderad","da":"opgraderet","fi":"korotettu","cs":"zvýšená","hu":"felminősítve","ro":"promovată","el":"αναβαθμισμένο","ru":"выше","tr":"yükseltilmiş","id":"dinaikkan","ms":"dinaikkan","vi":"nâng cấp","th":"เพิ่มคลาส","ja":"クラスアップ","ko":"등급 상향","zh-Hans":"升级","zh-Hant":"升級"},
 # Anzeigenamen der Modi und des unbenannten Kurses (OwnTimes.ModeText/CourseText).
 "automatic": {"de":"automatisch","fr":"automatique","es":"automático","it":"automatico","pt":"automático","nl":"automatisch","pl":"automatycznie","sv":"automatiskt","da":"automatisk","fi":"automaattinen","cs":"automaticky","hu":"automatikus","ro":"automat","el":"αυτόματα","ru":"автоматически","tr":"otomatik","id":"otomatis","ms":"automatik","vi":"tự động","th":"อัตโนมัติ","ja":"自動","ko":"자동","zh-Hans":"自动","zh-Hant":"自動"},
 "Rivals": {"de":"Rivalen","fr":"Rivaux","es":"Rivales","it":"Rivali","pt":"Rivais","nl":"Rivalen","pl":"Rywale","sv":"Rivaler","da":"Rivaler","fi":"Kilpailijat","cs":"Rivalové","hu":"Riválisok","ro":"Rivali","el":"Αντίπαλοι","ru":"Соперники","tr":"Rakipler","id":"Rival","ms":"Pesaing","vi":"Đối thủ","th":"คู่แข่ง","ja":"ライバル","ko":"라이벌","zh-Hans":"对手","zh-Hant":"對手"},
 "Solo": {"de":"Solo","fr":"Solo","es":"Individual","it":"Singolo","pt":"Solo","nl":"Solo","pl":"Solo","sv":"Solo","da":"Solo","fi":"Yksin","cs":"Sólo","hu":"Egyéni","ro":"Solo","el":"Μονός","ru":"Соло","tr":"Tek kişilik","id":"Solo","ms":"Solo","vi":"Chơi đơn","th":"เดี่ยว","ja":"ソロ","ko":"솔로","zh-Hans":"单人","zh-Hant":"單人"},
 "Co-op": {"de":"Koop","fr":"Coop","es":"Cooperativo","it":"Cooperativa","pt":"Cooperativo","nl":"Co-op","pl":"Kooperacja","sv":"Samarbete","da":"Samarbejde","fi":"Yhteistyö","cs":"Kooperace","hu":"Kooperatív","ro":"Cooperativ","el":"Συνεργατικό","ru":"Кооператив","tr":"Ortak","id":"Co-op","ms":"Koperatif","vi":"Hợp tác","th":"โคออป","ja":"協力","ko":"협동","zh-Hans":"合作","zh-Hant":"合作"},
 "Free roam": {"de":"Freies Fahren","fr":"Exploration libre","es":"Mundo libre","it":"Esplorazione libera","pt":"Exploração livre","nl":"Vrij rijden","pl":"Swobodna jazda","sv":"Fri körning","da":"Fri kørsel","fi":"Vapaa ajo","cs":"Volná jízda","hu":"Szabad felfedezés","ro":"Explorare liberă","el":"Ελεύθερη οδήγηση","ru":"Свободная езда","tr":"Serbest sürüş","id":"Jelajah bebas","ms":"Jelajah bebas","vi":"Tự do khám phá","th":"ขับอิสระ","ja":"フリーローム","ko":"자유 주행","zh-Hans":"自由漫游","zh-Hant":"自由漫遊"},
 "unknown": {"de":"unbekannt","fr":"inconnu","es":"desconocido","it":"sconosciuto","pt":"desconhecido","nl":"onbekend","pl":"nieznany","sv":"okänt","da":"ukendt","fi":"tuntematon","cs":"neznámý","hu":"ismeretlen","ro":"necunoscut","el":"άγνωστο","ru":"неизвестно","tr":"bilinmiyor","id":"tidak diketahui","ms":"tidak diketahui","vi":"không rõ","th":"ไม่ทราบ","ja":"不明","ko":"알 수 없음","zh-Hans":"未知","zh-Hant":"未知"},
 "Unnamed course": {"de":"Unbenannter Kurs","fr":"Parcours sans nom","es":"Circuito sin nombre","it":"Percorso senza nome","pt":"Percurso sem nome","nl":"Naamloos parcours","pl":"Trasa bez nazwy","sv":"Namnlös bana","da":"Unavngivet bane","fi":"Nimetön rata","cs":"Nepojmenovaná trať","hu":"Névtelen pálya","ro":"Traseu fără nume","el":"Ανώνυμη διαδρομή","ru":"Безымянная трасса","tr":"Adsız parkur","id":"Lintasan tanpa nama","ms":"Litar tanpa nama","vi":"Đường đua chưa đặt tên","th":"สนามไม่มีชื่อ","ja":"名称未設定のコース","ko":"이름 없는 코스","zh-Hans":"未命名赛道","zh-Hant":"未命名賽道"},
 # Leere Kacheln des Umriss-Overlays (CourseShapeHud): die Karte fehlt bzw. die eigene Runde.
 "no map harvested": {"de":"keine Karte erfasst","fr":"aucune carte capturée","es":"sin mapa capturado","it":"nessuna mappa acquisita","pt":"nenhum mapa capturado","nl":"geen kaart vastgelegd","pl":"brak zapisanej mapy","sv":"ingen karta hämtad","da":"intet kort hentet","fi":"karttaa ei tallennettu","cs":"mapa nezískána","hu":"nincs rögzített térkép","ro":"nicio hartă capturată","el":"δεν καταγράφηκε χάρτης","ru":"карта не снята","tr":"harita alınmadı","id":"peta belum diambil","ms":"tiada peta dirakam","vi":"chưa có bản đồ","th":"ยังไม่มีแผนที่","ja":"マップ未取得","ko":"지도 없음","zh-Hans":"未获取地图","zh-Hant":"未擷取地圖"},
 "not driven yet": {"de":"noch nicht gefahren","fr":"pas encore roulé","es":"aún no recorrido","it":"non ancora guidato","pt":"ainda não conduzido","nl":"nog niet gereden","pl":"jeszcze nie przejechano","sv":"inte körd än","da":"ikke kørt endnu","fi":"ei vielä ajettu","cs":"zatím neodjeto","hu":"még nem vezetett","ro":"încă nerulat","el":"δεν έχει οδηγηθεί ακόμα","ru":"ещё не пройдено","tr":"henüz sürülmedi","id":"belum dikendarai","ms":"belum dipandu","vi":"chưa chạy","th":"ยังไม่เคยขับ","ja":"未走行","ko":"아직 주행 안 함","zh-Hans":"尚未驾驶","zh-Hant":"尚未駕駛"},
 LANG: {
  "de":"{0} Runde(n) auf {1} Kurs(en), von {2} aufgezeichneten. Fahrhilfen, Schaltung und gültig/ungültig sind Angaben der Bestenliste, die die Telemetrie nicht sendet – sie können eigene Runden nicht filtern.",
  "fr":"{0} tour(s) sur {1} parcours, sur {2} enregistrés. Aides, boîte et valide/invalide sont des données du classement que la télémétrie n'envoie pas : elles ne peuvent pas filtrer vos tours.",
  "es":"{0} vuelta(s) en {1} circuito(s), de {2} grabadas. Ayudas, cambio y válida/inválida son datos de la clasificación que la telemetría no envía, así que no pueden filtrar tus vueltas.",
  "it":"{0} giro/i su {1} percorso/i, su {2} registrati. Aiuti, cambio e valido/non valido sono dati della classifica che la telemetria non invia, quindi non filtrano i tuoi giri.",
  "pt":"{0} volta(s) em {1} percurso(s), de {2} gravadas. Ajudas, caixa e válida/inválida são dados da classificação que a telemetria não envia, por isso não filtram as tuas voltas.",
  "nl":"{0} ronde(n) op {1} parcours, van {2} opgenomen. Rijhulp, versnellingsbak en geldig/ongeldig zijn ranglijstgegevens die de telemetrie niet stuurt, dus ze filteren je eigen ronden niet.",
  "pl":"{0} okrążeń na {1} trasach, z {2} zapisanych. Asysty, skrzynia i ważne/nieważne to dane rankingu, których telemetria nie wysyła, więc nie filtrują Twoich okrążeń.",
  "sv":"{0} varv på {1} banor, av {2} inspelade. Hjälpmedel, växellåda och giltig/ogiltig är topplistedata som telemetrin inte skickar, så de kan inte filtrera dina egna varv.",
  "da":"{0} omgang(e) på {1} bane(r) af {2} optaget. Hjælpemidler, gearkasse og gyldig/ugyldig er ranglistedata, som telemetrien ikke sender, så de kan ikke filtrere dine egne omgange.",
  "fi":"{0} kierrosta {1} radalla, {2} tallennetusta. Avustimet, vaihteisto ja kelvollinen/hylätty ovat tulostaulun tietoja, joita telemetria ei lähetä, joten niillä ei voi suodattaa omia kierroksia.",
  "cs":"{0} kol na {1} tratích z {2} zaznamenaných. Asistence, převodovka a platné/neplatné jsou údaje žebříčku, které telemetrie neposílá, takže vlastní kola filtrovat nemohou.",
  "hu":"{0} kör {1} pályán, {2} rögzítettből. A segédletek, a váltó és az érvényes/érvénytelen a ranglista adatai, amelyeket a telemetria nem küld, így a saját köreidet nem szűrhetik.",
  "ro":"{0} tur(uri) pe {1} traseu(e), din {2} înregistrate. Asistențele, cutia și valid/invalid sunt date ale clasamentului pe care telemetria nu le trimite, deci nu pot filtra tururile tale.",
  "el":"{0} γύρος/οι σε {1} διαδρομή/ές, από {2} καταγεγραμμένους. Βοηθήματα, κιβώτιο και έγκυρο/άκυρο είναι στοιχεία κατάταξης που η τηλεμετρία δεν στέλνει, άρα δεν φιλτράρουν τους γύρους σας.",
  "ru":"{0} кругов на {1} трассах из {2} записанных. Помощники, коробка и зачёт/незачёт — данные таблицы лидеров, которых телеметрия не передаёт, поэтому по ним нельзя фильтровать свои круги.",
  "tr":"{2} kayıttan {1} parkurda {0} tur. Yardımlar, şanzıman ve geçerli/geçersiz, telemetrinin göndermediği sıralama bilgileridir; kendi turlarınızı filtreleyemezler.",
  "id":"{0} putaran di {1} lintasan, dari {2} yang direkam. Bantuan, transmisi, dan sah/tidak sah adalah data papan peringkat yang tidak dikirim telemetri, jadi tidak bisa menyaring putaran Anda.",
  "ms":"{0} pusingan di {1} litar, daripada {2} yang dirakam. Bantuan, kotak gear dan sah/tidak sah ialah data papan pendahulu yang tidak dihantar telemetri, jadi tidak boleh menapis pusingan anda.",
  "vi":"{0} vòng trên {1} đường đua, trong {2} vòng đã ghi. Hỗ trợ lái, hộp số và hợp lệ/không hợp lệ là dữ liệu bảng xếp hạng mà telemetry không gửi, nên không thể lọc vòng của bạn.",
  "th":"{0} รอบใน {1} สนาม จาก {2} รอบที่บันทึก ตัวช่วย เกียร์ และถูกต้อง/ไม่ถูกต้อง เป็นข้อมูลกระดานอันดับที่เทเลเมทรีไม่ได้ส่ง จึงกรองรอบของคุณไม่ได้",
  "ja":"記録 {2} 周のうち {1} コースで {0} 周。アシスト、トランスミッション、有効/無効はテレメトリが送らないランキング情報のため、自分の周回の絞り込みには使えません。",
  "ko":"기록된 {2}랩 중 {1}개 코스의 {0}랩. 보조 장치, 변속기, 유효/무효는 텔레메트리가 보내지 않는 순위표 정보라서 내 랩을 거를 수 없습니다.",
  "zh-Hans":"共记录 {2} 圈，其中 {1} 条赛道上的 {0} 圈。辅助、变速箱和有效/无效是遥测不发送的排行榜信息，无法用来筛选你自己的圈。",
  "zh-Hant":"共記錄 {2} 圈，其中 {1} 條賽道上的 {0} 圈。輔助、變速箱和有效/無效是遙測不傳送的排行榜資訊，無法用來篩選你自己的圈。",
 },
}

CODES = ["de","fr","es","it","pt","nl","pl","sv","da","fi","cs","hu","ro","el",
            "ru","tr","id","ms","vi","th","ja","ko","zh-Hans","zh-Hant"]

ZUSATZ = {code: {k: v[code] for k, v in T.items()} for code in CODES}
ZUSATZ["zh"] = ZUSATZ["zh-Hans"]
